### ISSUE TITLE
[Question] We are thinking of forking the project to use moshi instead of gson.

### ISSUE THREAD

**Issue by sid-dob** [rudderlabs/rudder-sdk-android#56]
We use "Moshi" as the serialization library in our project and are looking to avoid the huge method count and dependency on gson.

Could you advise us on a possible way to do this ? or any other feedback you might have regarding this.

Currently, we are thinking of replacing the Model Files with Moshi related annotations/data classes. 

Let us know what you think about this.

Thanks

**Comment by ruchiramoitra** [comment]
Yes, you can use Moshi library with our project.
You need to implement the following in the core build file: 

implementation 'com.squareup.moshi:moshi:1.9.2'
implementation 'com.squareup.moshi:moshi-adapters:1.9.2'

An example of using Moshi library instead of Gson:

Moshi moshi = new Moshi.Builder().build();
JsonAdapter<RudderMessage> jsonAdapter = moshi.adapter(RudderMessage.class);
String eventJson = jsonAdapter.toJson(message);

You will need to change all the @SerializedName("name") to @Json(name = "name") and you are good to go. 

For more information please follow: 

https://www.baeldung.com/java-json-moshi
